### ISSUE TITLE
Create a new job as a slide down from the top of the screen

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#24]
- [x] make a new job window
- [x] make the job window close on save or cancel
- [x] better styling of the sections
- [x] add a booking number field
- [x] use a job prefix (JB123124)
- [x] create a job numbering scheme
- [x] save a new job to the database 
- [x] move the asset from the controller to the service
- [x] on job open, close the job info & feed
- [x] error handling
- [x] add all other fields (with validation)
  - [x] finish validation
  - [x] make the radio buttons work
- [x] make the calendar view the day of the first booking of the job
- [x] add/delete assets
- [x] refactor search controller to service
- [x] e2e tests
- [x] have a look at that mock in util.js
- [x] add a 404

**Comment by StevenGBrown** [comment]
This appears in the JavaScript console when starting the app:

```
Error: [$injector:unpr] Unknown provider: SearchServiceProvider <- SearchService
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=SearchServiceProvider%20%3C-%20SearchService
    at http://localhost:9200/bower_components/angular/angular.js:68:12
    at http://localhost:9200/bower_components/angular/angular.js:4511:19
    at Object.getService [as get] (http://localhost:9200/bower_components/angular/angular.js:4664:39)
    at http://localhost:9200/bower_components/angular/angular.js:4516:45
    at getService (http://localhost:9200/bower_components/angular/angular.js:4664:39)
    at injectionArgs (http://localhost:9200/bower_components/angular/angular.js:4688:58)
    at Object.instantiate (http://localhost:9200/bower_components/angular/angular.js:4730:18)
    at $controller (http://localhost:9200/bower_components/angular/angular.js:10369:28)
    at Object.<anonymous> (http://localhost:9200/bower_components/angular-ui-router/release/angular-ui-router.js:3897:28)
    at http://localhost:9200/bower_components/angular/angular.js:1247:18 <div ui-view="search" class="m-b ng-scope" data-ng-animate="1">
```

**Comment by StevenGBrown** [comment]
I longer see the JavaScript error with latest version 2550f68
