### ISSUE TITLE
Job - add a title field

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#61]

**Comment by bwobbones** [comment]
This title should be limited to 50 characters as this title will need to appear where ever the job number does.

make mandatory
limit to 50 chars

**Comment by bwobbones** [comment]
@kirk93 i get this error after you made this fix:

VM4761:27 TypeError: Cannot read property 'jobNumber' of undefined
    at Scope.SearchCtrl.vm.label (http://localhost:9200/search/controller/searchController.js:20:28)
    at Object.fn [as viewMapper](eval at compile %28http://localhost:9200/bower_components/angular/angular.js:14817:15%29, <anonymous>:4:270)
    at Array.<anonymous> (http://localhost:9200/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:7058:43)
    at ngModelWatch (http://localhost:9200/bower_components/angular/angular.js:27810:36)
    at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1316:35)
    at Scope.$digest (http://localhost:9200/bower_components/angular/angular.js:17515:34)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1364:23)
    at Scope.$apply (http://localhost:9200/bower_components/angular/angular.js:17790:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1427:22)
    at done (http://localhost:9200/bower_components/angular/angular.js:11831:47)

**Comment by StevenGBrown** [comment]
Complete
